### ISSUE TITLE
The conversion from bib file to list of papers doesn't handle underscores

### ISSUE THREAD

**Issue by alexjbest** [leanprover-community/leanprover-community.github.io#130]
Consequently the link to "hygienic macro expansion" on https://leanprover-community.github.io/papers.html is broken, it contains an extra slash that shouldn't be there.

Somewhere in the tex->html conversion in make_site we should handle that `_` must be written as `\_` in a tex url, around line 300 https://github.com/leanprover-community/leanprover-community.github.io/blob/newsite/make_site.py#L300

**Comment by PatrickMassot** [comment]
Thanks Alex. That bug is now fixed, but the process is very hacky, so maybe I created other bugs.
