### ISSUE TITLE
100 theorems

### ISSUE THREAD

**Issue by bryangingechen** [leanprover-community/leanprover-community.github.io#14]
We should put @fpvandoorn's ["100 theorems" list](https://github.com/leanprover-community/mathlib/blob/100-thms/docs/100-theorems.md) on the website.

**Comment by jcommelin** [comment]
https://gist.github.com/jcommelin/61d3cc00744aa0b445c9f182d0044885 is a yaml version of the list

**Comment by jcommelin** [comment]
The yaml file is now at: https://github.com/leanprover-community/leanprover-community.github.io/blob/newsite/data/100.yaml

**Comment by RaitoBezarius** [comment]
Shouldn't this issue be closed as the 100 theorems page is generated?

**Comment by bryangingechen** [comment]
Sure, I think the original issue is solved.

TODO: someone should perhaps contact Freek Wiedijk and ask him to change the Lean links to point to https://leanprover-community.github.io/100.html
