### ISSUE TITLE
markdown to html conversion mangles `[name](url).`

### ISSUE THREAD

**Issue by JasonGross** [leanprover-community/leanprover-community.github.io#175]
The text `For a faster paced and broader dive, you can get the [tutorials project](https://github.com/leanprover-community/tutorials).` shows up in https://leanprover-community.github.io/learn.html but not https://github.com/leanprover-community/leanprover-community.github.io/blob/newsite/templates/learn.md and links to the non-existent page `https://github.com/leanprover-community/tutorials).`  Links which are not immediately followed by `.` do not suffer this problem.

**Comment by bryangingechen** [comment]
Ugh, this is an unfortunate bug in https://github.com/leanprover-community/leanprover-community.github.io/commit/7510f325a86c84aee39e568dcdf70ebeb6f21e74

Thanks for reporting, I'll see what I can do.

**Comment by JasonGross** [comment]
Perhaps the solution is to percent-encode `)` wherever it appears in URLs and to remove `)` from the regex?

**Comment by bryangingechen** [comment]
Right, reverting that commit is probably the simplest option. The same code was used to generate links from raw URLs in mathlib doc strings. I changed it because it was running into trouble with the URLs [here](https://leanprover-community.github.io/mathlib_docs/order/ideal.html#references), but those should probably just be percent encoded.

**Comment by robertylewis** [comment]
Even GitHub's markdown parsing doesn't like those in the source: https://github.com/leanprover-community/mathlib/blob/97d13d7561ef9c9a21587cf62324f8b2d215a7f8/src/order/ideal.lean

**Comment by bryangingechen** [comment]
> Even GitHub's markdown parsing doesn't like those in the source: https://github.com/leanprover-community/mathlib/blob/97d13d7561ef9c9a21587cf62324f8b2d215a7f8/src/order/ideal.lean

They seem fine on my end, but maybe I'm missing something?

<img width="688" alt="Screen Shot 2021-03-05 at 11 32 10 AM" src="https://user-images.githubusercontent.com/5209952/110144541-7374a700-7da6-11eb-8744-63ed07094e37.png">

**Comment by robertylewis** [comment]
Oh, this could be a feature of the Refined GitHub extension, I'm not sure.

![image](https://user-images.githubusercontent.com/4967469/110144779-00385880-7dd9-11eb-8b8f-71c4a5765c78.png)

**Comment by bryangingechen** [comment]
Ah, that looks like a convenient extension. In any case, I'll revert the regex change here and in `doc-gen` and then open a PR fixing the URLs in mathlib later today.

**Comment by bryangingechen** [comment]
This should be fixed now. Thanks again!
