### ISSUE TITLE
Can we adopt your Zulip archive export tool?

### ISSUE THREAD

**Issue by timabbott** [leanprover-community/leanprover-community.github.io#2]
Hey, I run the Zulip project, and I was wondering if you folks would be interested in helping migrate your data import tool to something that lives in https://github.com/zulip/python-zulip-api that we document as generally available to other projects that want a public archive?

If so, I'd love to have some of our core contributors collaborate with the author to integrate it there (and then you can just use our project as a `pip` dependency here).

We have plans for a more built-in experience in Zulip, but I was realizing even if we provide that, this sort of "generate HTML" thing is both more customizable and maybe a cleaner approach for a final public archive of a Zulip organization being closed down, so we probably want something of this form available as a tool to use with Zulip anyway.

**Comment by robertylewis** [comment]
> Can we adopt your Zulip archive export tool?

Short answer: yes, of course, do whatever you'd like with it!

It's almost the end of the semester here and I'm swamped with teaching/exam prep duties. As soon as that's over I have a month straight of conference travel, so I won't have a lot of time to devote to this in the near future. But I'd be happy to see this adapted, and I'll help however I can.

I should admit that not a ton of thought went into the export tool -- it was a "good enough" solution for what we wanted to do at the time. If it ends up rewritten from scratch, I'd be neither surprised nor disappointed. :)

**Comment by timabbott** [comment]
Cool, makes sense.  I'll keep you updated on our efforts.

**Comment by robertylewis** [comment]
@timabbott I finally found a bit of time to come back to this. I've moved the archive script to its own repository (https://github.com/robertylewis/zulip_archive) and refactored a bit, at least to indicate what is customizable.

I'm no Python developer, and my previous disclaimer still stands. But at least this version is disentangled from the rest of our Jekyll setup here.

**Comment by timabbott** [comment]
Awesome, thanks @robertylewis!  I'll see if I can recruit someone from the community to help move that forward.
