### ISSUE TITLE
Broken links in documentation (category_theory)

### ISSUE THREAD

**Issue by kevinsullivan** [leanprover-community/leanprover-community.github.io#267]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover-community/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover-community/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover-community/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover-community/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Most of the hyperlinks on this page are broken: https://leanprover-community.github.io/theories/category_theory.html

### Steps to Reproduce

1. Just try them.

**Expected behavior:** [What you expect to happen]

Not 404.

**Actual behavior:** [What actually happens]

404.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Reliably

### Versions

Version 3 community, online.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by gebner** [comment]
See also #262.  We should probably do some link-checking during CI like we do for the undergrad topics, etc.
