### ISSUE TITLE
100 theorems links can be simplified

### ISSUE THREAD

**Issue by robertylewis** [leanprover-community/leanprover-community.github.io#32]
No time at the moment to do it myself, but just wanted to leave a public message that the 100 theorems links can be simplified. No need to store the directory, the random `.html#`, etc. Just the declaration name (e.g. `complex.exists_root`) will be enough. The generation can create links like

https://leanprover-community.github.io/mathlib_docs/find/complex.exists_root
https://leanprover-community.github.io/mathlib_docs/find/complex.exists_root/src

(Of course this only works for things in mathlib, but so does the current scheme, and this is more robust to refactorings.)

**Comment by RaitoBezarius** [comment]
Wow, that seems a good thing for #28 and #33

**Comment by bryangingechen** [comment]
This was fixed by #54.
