### ISSUE TITLE
Broken link in `/install/project.html`

### ISSUE THREAD

**Issue by Rida-Hamadani** [leanprover-community/leanprover-community.github.io#489]
There is a broken link in [this ](https://leanprover-community.github.io/install/project.html#hosting-your-project-on-github) section, it gives a 404 error: https://leanprover-community.github.io/ci.html.

**Comment by bryangingechen** [comment]
This will be fixed when https://github.com/leanprover-community/leanprover-community.github.io/pull/487 is merged.
